language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
dist: trusty
sudo: required
node_js:
  - "stable"
  - "10"
  - "9"
stages:
  - |
    setup
    test
    document
    name: deploy
    if: branch = master
    name: release
    if: branch = master
jobs:
  include:
    - stage: setup
      script: 
        - npm i -g typescript@latest
        - npm i -g coveralls
    - stage: test
      name: "Run unit and smoke tests"
      script: npm run test:all
      script: npm run smoketest
      name: "Run smoketests"
    - stage: document
      name: "Generate API documents"
      script: npm run docs
    - stage: deploy
      name: "Deploy Github Pages"
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GH_TOKEN
        keep-history: true
        on:
          branch: master
      script: npm run coverage
    - stage: release
      after_success: 
        - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
git:
  depth: 3
