name: Mark stale issues and pull requestrs
on:
  schedule:
  - cron: "* * 1 * *"
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has been marked stale as there has been no activity on it recently.'
        stale-pr-message: 'This pull request has been marked stale as there has been no activity on it recently.'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
